service: iopipe-lib-py-master-acceptance-test

provider:
  name: aws
  runtime: python2.7
  stage: prod
  region: us-west-2
  role: ${env:IAM_ROLE}

functions:
  callback:
    handler: handler.callback
    environment:
      IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    events:
      - schedule: rate(10 minutes)
  contextSuccess:
    handler: handler.succeed
    environment:
      IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    events:
      - schedule: rate(10 minutes)
  contextFail:
    handler: handler.fail
    environment:
      IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    events:
      - schedule: rate(10 minutes)
  contextDone:
    handler: handler.done
    environment:
      IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    events:
      - schedule: rate(10 minutes)
  py3callback:
    handler: handler.callback
    runtime: python3.6
    environment:
      IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    events:
      - schedule: rate(10 minutes)
  py3contextSuccess:
    handler: handler.succeed
    runtime: python3.6
    environment:
      IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    events:
      - schedule: rate(10 minutes)
  py3contextFail:
    handler: handler.fail
    runtime: python3.6
    environment:
      IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    events:
      - schedule: rate(10 minutes)
  py3contextDone:
    handler: handler.done
    runtime: python3.6
    environment:
      IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    events:
      - schedule: rate(10 minutes)
